version: '3'
services: 
  app:
    build: ./app
    ports: 
      - 8443:8443
      - 8080:8080
    volumes:
      - ./app:/works/app
    environment: 
      - PASSWORD=dummy_password
    command: /works/code-server --allow-http --auth password --port 8443 /works/app --cert 

